### ISSUE TITLE
it's really work ?

### ISSUE THREAD

**Issue by oktecko** [oktecko/greenify#2]
any one know it's really work ?

**Comment by bugbounted2022** [comment]
hello again [oktecko](https://github.com/oktecko),
I think this fork is outdate & can suspend your account , use it at your own risk .
& also may bee patched,
you can find alternative update repo with sort by recently updated filter in search all github result.
finest regards
goodbye

**Comment by bugbounted2022** [comment]
> any one know it's really work ?

hello again [oktecko](https://github.com/oktecko),
I think this fork is outdate & can suspend your account , use it at your own risk .
& also may bee patched,
you can find alternative update repo with sort by recently updated filter in search all github result.
finest regards
goodbye
